**TASK:01**

In [ ]:
import numpy as np
Y=np.array([[2,4,6,8],[10,12,14,16],[18,20,22,24],[26,28,30,32]])
print()
print('Y=\n', Y)
print()


Y=
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]



**TASK:02**

In [ ]:
import numpy as np
X = np.arange(1,26).reshape(5,5)
Y = X[X % 2 == 1]
print(X)
print(Y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


**TASK:03**

In [ ]:
import numpy as np
X = np.ones((4, 4)) * np.arange(1, 5)
print(X)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
